# Generated by Django 5.1.2 on 2026-01-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='interval',
            field=models.PositiveIntegerField(help_text='Interval in minutes'),
        ),
    ]
